<?php
return [
    'team_info' => [
        [
            'name'=> 'Nguyễn Trí Hoàng',
            'facebook'=> 'ruanhuang123',
            'email' =>'ng.tri.hoang2004ct@gmail.com',
            'imagePath'=> 'images/team_images/Hoang.jpg',
            'workplace'=>'CTU',
            'position'=>'Director',
            'biography' => '',
        ],
        [
            'name'=> 'Hoàng Tuấn Anh',
            'facebook'=> 'anh.hoangtuan.5477',
            'email' =>'',
            'imagePath'=> 'images/team_images/anh.jpg',
            'workplace'=>'CTU',
            'position'=>'Founder',
            'biography' => '',
        ],
        [
            'name'=> 'Phạm Chí Thịnh',
            'facebook'=> 'thinh.pham.960143',
            'email' =>'',
            'imagePath'=> 'images/team_images/thinh.jpg',
            'workplace'=>'CTU',
            'position'=>'Technical manager',
            'biography' => '',
        ],
        [
            'name'=> 'Trần Nguyên Hiền',
            'facebook'=> 'profile.php?id=100078640101228',
            'email' =>'',
            'imagePath'=> 'images/team_images/hien.jpg',
            'workplace'=>'CTU',
            'position'=>'Technical manager',
            'biography' => '',
        ],
        [
            'name'=> 'Võ Quốc Huy',
            'facebook'=> 'profile.php?id=100092557951607',
            'email' =>'',
            'imagePath'=> 'images/team_images/huy.jpg',
            'workplace'=>'CTU',
            'position'=>'Mechanical manager',
            'biography' => '',
        ],
        [
            'name'=> 'Đoàn Ngọc Khả Vy',
            'facebook'=> 'DNKhaVy',
            'email' =>'',
            'imagePath'=> 'images/team_images/vy.jpg',
            'workplace'=>'CTU',
            'position'=>'Marketing Manager',
            'biography' => '',
        ],
        [
            'name'=> 'Nguyễn Thị Kim Trân',
            'facebook'=> '',
            'email' =>'nguyentran5304@gmail.com',
            'imagePath'=> 'images/team_images/',
            'workplace'=>'CTU',
            'position'=>'Face ID technican',
            'biography' => '',
        ],
        [
            'name'=> 'Nguyễn Hoàng Vũ',
            'facebook'=> '',
            'email' =>'',
            'imagePath'=> 'images/team_images/',
            'workplace'=>'CTU',
            'position'=>'Supporter',
            'biography' => '',
        ],
    ]
];