
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: production
      APP_KEY: base64:ewurUgd2FyPYitra5omyeWxy0V3QS6Wr8K9N3tYXy+M=
      # - LOG_CHANNEL=stderr
      # DB_CONNECTION=pgsql
      # DB_HOST=${SUPABASE_HOST}
      # DB_DATABASE=${SUPABASE_DB}
      # DB_USERNAME=${SUPABASE_USER}
      # DB_PASSWORD=${SUPABASE_PASSWORD}
      # DB_CONNECTION: sqlite
      # DB_URL: postgresql://postgres:BaristaWeb12345@db.safsghcjddrtiyqpyxqe.supabase.co:5432/postgres
      # DB_URL: psql -h db.safsghcjddrtiyqpyxqe.supabase.co -p 5432 -d postgres -U postgres
      DB_CONNECTION: pgsql
      # DB_HOST: db.safsghcjddrtiyqpyxqe.supabase.co
      DB_HOST: db.safsghcjddrtiyqpyxqe.supabase.co

      # DB_HOST: postgresql://postgres:BaristaWeb12345@db.safsghcjddrtiyqpyxqe.supabase.co:5432/postgres
      DB_PORT: 5432  
      DB_DATABASE: postgres 
      DB_USERNAME: postgres 
      DB_PASSWORD: BaristaWeb12345  
      DB_SSL: require


