
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: production
      APP_KEY: base64:ewurUgd2FyPYitra5omyeWxy0V3QS6Wr8K9N3tYXy+M=
      # - LOG_CHANNEL=stderr
      # DB_CONNECTION=pgsql
      # DB_HOST=${SUPABASE_HOST}
      # DB_DATABASE=${SUPABASE_DB}
      # DB_USERNAME=${SUPABASE_USER}
      # DB_PASSWORD=${SUPABASE_PASSWORD}
